# Generated by Django 4.2.5 on 2023-11-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0025_alter_video_name'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('movie', 'show', 'seat')},
        ),
    ]
