# Generated by Django 4.2.5 on 2023-09-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
