# Generated by Django 4.2.5 on 2023-09-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_director_director_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='director_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.director', to_field='director_name'),
        ),
    ]
