# Generated by Django 4.2.5 on 2023-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_remove_movie_director_id_movie_director_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
