# Generated by Django 4.2.5 on 2023-09-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
