# Generated by Django 4.2.5 on 2023-09-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_movie_movie_api_id_alter_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
    ]
