# Generated by Django 4.2.5 on 2023-09-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_movie_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
