# Generated by Django 4.2.5 on 2023-09-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_remove_movie_cast_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
