# Generated by Django 4.2.5 on 2023-10-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_alter_director_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_api_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
