# Generated by Django 4.2.5 on 2023-10-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_alter_cast_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
