# Generated by Django 4.2.5 on 2023-11-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_alter_movie_genre_alter_movie_tmdb_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_api_id', models.IntegerField(null=True, unique=True)),
                ('release_date', models.DateField(null=True)),
                ('genre', models.CharField(max_length=80, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tmdb_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('movie_poster', models.ImageField(default='default.jpg', upload_to='movie_posters')),
                ('director_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.director', to_field='director_name')),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.movie')),
            ],
        ),
    ]
