# Generated by Django 4.2.5 on 2023-11-03 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_alter_movie_genre_alter_movie_tmdb_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.movie')),
            ],
        ),
    ]
