# Generated by Django 4.2.5 on 2023-11-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_trendingmovies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingmovies',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RemoveField(
            model_name='trendingmovies',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trendingmovies',
            name='director_name',
        ),
        migrations.RemoveField(
            model_name='trendingmovies',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='trendingmovies',
            name='movie_api_id',
        ),
        migrations.RemoveField(
            model_name='trendingmovies',
            name='movie_poster',
        ),
        migrations.RemoveField(
            model_name='trendingmovies',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='trendingmovies',
            name='tmdb_rating',
        ),
    ]
