# Generated by Django 4.2.5 on 2023-11-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_trendingmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='in_theatres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='trending',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TrendingMovies',
        ),
    ]
