# Generated by Django 4.2.5 on 2023-11-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0019_movie_in_theatres_movie_trending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
