# Generated by Django 4.2.5 on 2023-11-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0021_actors_remove_cast_cast_cast_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='actor_name',
            field=models.CharField(max_length=30),
        ),
    ]
