# Generated by Django 4.2.5 on 2023-11-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0025_alter_video_name'),
        ('users', '0002_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='films.movie'),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
